In [1]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("../database/database.db")

In [2]:
#load tables
sales = pd.read_sql_query("SELECT * FROM Sales", conn)
external = pd.read_sql_query("SELECT * FROM External_Factors", conn)

In [3]:
#total sales
pd.read_sql_query("""
SELECT SUM(weekly_sales) AS total_sales
FROM Sales;
""", conn)

    total_sales
0  6.737219e+09

In [4]:
#top stores
pd.read_sql_query("""
SELECT store_id, SUM(weekly_sales) AS total
FROM Sales
GROUP BY store_id
ORDER BY total DESC;
""", conn)

    store_id         total
0         20  3.013978e+08
1          4  2.995440e+08
2         14  2.889999e+08
3         13  2.865177e+08
4          2  2.753824e+08
5         10  2.716177e+08
6         27  2.538559e+08
7          6  2.237561e+08
8          1  2.224028e+08
9         39  2.074455e+08
10        19  2.066349e+08
11        31  1.996139e+08
12        23  1.987506e+08
13        24  1.940160e+08
14        11  1.939628e+08
15        28  1.892637e+08
16        41  1.813419e+08
17        32  1.668192e+08
18        18  1.551147e+08
19        22  1.470756e+08
20        12  1.442872e+08
21        26  1.434164e+08
22        34  1.382498e+08
23        40  1.378703e+08
24        35  1.315207e+08
25         8  1.299512e+08
26        17  1.277821e+08
27        45  1.123953e+08
28        21  1.081179e+08
29        25  1.010612e+08
30        43  9.056544e+07
31        15  8.913368e+07
32         7  8.159828e+07
33        42  7.956575e+07
34         9  7.778922e+07
35        29  7.714155e+07
36        16  7.425243e+07
37        37  7.420274e+07
38        30  6.271689e+07
39         3  5.758674e+07
40        38  5.515963e+07
41        36  5.341221e+07
42         5  4.547569e+07
43        44  4.329309e+07
44        33  3.716022e+07

In [5]:
#monthely trend
pd.read_sql_query("""
SELECT SUBSTR(date,1,7) AS month,
       SUM(weekly_sales) AS sales
FROM Sales
GROUP BY month
ORDER BY month;
""", conn)

      month         sales
0      None  4.018647e+09
1   2010-01  4.223988e+07
2   2010-02  9.934132e+07
3   2010-03  9.710329e+07
4   2010-04  5.018854e+07
5   2010-05  1.424042e+08
6   2010-06  4.820500e+07
7   2010-07  4.850324e+07
8   2010-08  4.510297e+07
9   2010-09  9.526482e+07
10  2010-10  1.013012e+08
11  2010-11  4.782655e+07
12  2010-12  1.403869e+08
13  2011-01  9.103751e+07
14  2011-02  9.476718e+07
15  2011-03  4.877199e+07
16  2011-04  1.417893e+08
17  2011-05  4.801547e+07
18  2011-06  4.686196e+07
19  2011-07  8.998748e+07
20  2011-08  9.374673e+07
21  2011-09  1.023244e+08
22  2011-10  4.766973e+07
23  2011-11  1.404377e+08
24  2011-12  4.624957e+07
25  2012-01  4.828165e+07
26  2012-02  4.686103e+07
27  2012-03  9.357151e+07
28  2012-04  4.712420e+07
29  2012-05  4.756664e+07
30  2012-06  1.497108e+08
31  2012-07  4.833006e+07
32  2012-08  4.965117e+07
33  2012-09  4.748045e+07
34  2012-10  9.741286e+07
35  2012-11  4.692588e+07
36  2012-12  4.612851e+07

In [7]:
#economic impact
pd.read_sql_query("""
SELECT 
    s.store_id,
    AVG(s.weekly_sales) AS avg_sales,
    AVG(e.unemployment) AS avg_unemployment
FROM Sales s
JOIN External_Factors e
ON s.store_id = e.store_id AND s.date = e.date
GROUP BY s.store_id;
""", conn)

    store_id     avg_sales  avg_unemployment
0          1  1.601845e+06          7.629509
1          2  1.951955e+06          7.653000
2          3  4.131402e+05          7.196526
3          4  2.088557e+06          6.036737
4          5  3.244423e+05          6.314772
5          6  1.588922e+06          6.633035
6          7  5.673988e+05          8.604772
7          8  9.231508e+05          6.107912
8          9  5.524182e+05          6.120526
9         10  1.905260e+06          8.403439
10        11  1.372474e+06          7.196526
11        12  1.017966e+06         13.168386
12        13  1.998168e+06          7.044000
13        14  2.075189e+06          8.653719
14        15  6.228744e+05          7.995684
15        16  5.153451e+05          6.494175
16        17  9.008318e+05          6.559737
17        18  1.096185e+06          8.852544
18        19  1.468692e+06          7.995684
19        20  2.169370e+06          7.385561
20        21  7.343721e+05          7.653000
21        22  1.036432e+06          8.081667
22        23  1.392810e+06          4.824877
23        24  1.395030e+06          8.434035
24        25  7.029491e+05          7.385561
25        26  1.037307e+06          7.886386
26        27  1.782782e+06          7.998772
27        28  1.434570e+06         13.168386
28        29  5.404586e+05          9.823439
29        30  4.412639e+05          7.653000
30        31  1.399383e+06          7.653000
31        32  1.152726e+06          8.604772
32        33  2.673390e+05          8.579561
33        34  9.659634e+05          9.944351
34        35  9.252588e+05          8.791333
35        36  3.797818e+05          7.902140
36        37  5.239235e+05          7.902140
37        38  4.044115e+05         13.168386
38        39  1.435258e+06          7.902140
39        40  1.004469e+06          4.824877
40        41  1.266986e+06          6.992561
41        42  5.846553e+05          8.403439
42        43  6.435285e+05          9.944351
43        44  3.025489e+05          6.779877
44        45  7.858437e+05          8.653719

### Insight:
Stores with higher unemployment rates tend to show lower average sales, indicating a negative correlation between economic conditions and retail performance.